// lib/featureMap.ts
// Diupdate sesuai backend v2.0 — fitur dari endpoint /features
// RF: 34 fitur | MI: 35 fitur | Full: 37 fitur
// CATATAN: HadAngina dihapus dari semua model (target variable, bukan input)

export const featureMap = {
  // ============================================
  // MODEL RANDOM FOREST (34 FITUR)
  // ============================================
  "random-forest": [
    "bmi",
    "weightinkilograms",
    "heightinmeters",
    "agecategory",
    "sleephours",
    "physicalhealthdays",
    "tetanuslast10tdap",
    "generalhealth",
    "mentalhealthdays",
    "removedteeth",
    "smokerstatus",
    "chestscan",
    "covidpos",
    "haddiabetes",
    "alcoholdrinkers",
    "raceethnicitycategory",
    "ecigaretteusage",
    "fluvaxlast12",
    "hivtesting",
    "pneumovaxever",
    "physicalactivities",
    "hadarthritis",
    "difficultywalking",
    "hadstroke",
    "hadcopd",
    "sex",
    "hadkidneydisease",
    "hadasthma",
    "hadskincancer",
    "haddepressivedisorder",
    "deaforhardofhearing",
    "difficultyconcentrating",
    "lastcheckuptime",
    "blindorvisiondifficulty",
  ],

  // ============================================
  // MODEL MUTUAL INFORMATION (35 FITUR)
  // ============================================
  "mi": [
    "physicalactivities",
    "alcoholdrinkers",
    "fluvaxlast12",
    "chestscan",
    "lastcheckuptime",
    "sex",
    "pneumovaxever",
    "raceethnicitycategory",
    "generalhealth",
    "agecategory",
    "hadarthritis",
    "removedteeth",
    "hivtesting",
    "tetanuslast10tdap",
    "sleephours",
    "difficultywalking",
    "covidpos",
    "haddiabetes",
    "smokerstatus",
    "physicalhealthdays",
    "hadcopd",
    "hadkidneydisease",
    "hadstroke",
    "haddepressivedisorder",
    "deaforhardofhearing",
    "difficultyerrands",
    "hadskincancer",
    "hadasthma",
    "weightinkilograms",
    "heightinmeters",
    "difficultyconcentrating",
    "blindorvisiondifficulty",
    "ecigaretteusage",
    "difficultydressingbathing",
    "bmi",
  ],

  // ============================================
  // MODEL CNN-LSTM FULL (37 FITUR)
  // ============================================
  "cnn-lstm": [
    "sex",
    "generalhealth",
    "physicalhealthdays",
    "mentalhealthdays",
    "lastcheckuptime",
    "physicalactivities",
    "sleephours",
    "removedteeth",
    "hadstroke",
    "hadasthma",
    "hadskincancer",
    "hadcopd",
    "haddepressivedisorder",
    "hadkidneydisease",
    "hadarthritis",
    "haddiabetes",
    "deaforhardofhearing",
    "blindorvisiondifficulty",
    "difficultyconcentrating",
    "difficultywalking",
    "difficultydressingbathing",
    "difficultyerrands",
    "smokerstatus",
    "ecigaretteusage",
    "chestscan",
    "raceethnicitycategory",
    "agecategory",
    "heightinmeters",
    "weightinkilograms",
    "bmi",
    "alcoholdrinkers",
    "hivtesting",
    "fluvaxlast12",
    "pneumovaxever",
    "tetanuslast10tdap",
    "highrisklastyear",
    "covidpos",
  ],
};